apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis
spec:
  metrics:
    - name: success-share
      interval: 1m
      successCondition: len(result) == 0 || result[0] >= 0.99
      failureLimit: 0
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(sample_app_requests_count{service="canary", success="true"}[1m])) by (service) /
            sum(rate(sample_app_requests_count{service="canary"}[1m])) by (service)
            unless sum(rate(sample_app_requests_count{service="canary"}[1m])) by (service) == 0
