apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-app
  namespace: argocd
spec:
  destination:
    namespace: blue-green
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: blue-green
    repoURL: "https://github.com/mohammadrony/argo-practice.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
